@url= localhost
@apptserviceDaprPort = 5010

###
# @name scheduleRequest
POST http://{{url}}:{{apptserviceDaprPort}}/v1.0/invoke/appointment-service/method/v1/schedule HTTP/1.1
Content-Type: application/json

{
    "AppointmentDateTime": "2024-01-11T08:00:00",
    "PatientFirstName": "Matt",
    "PatientLastName": "Sheehan",
    "Practitioner": "Dr. Acula"
}

###
@appointmentId = {{scheduleRequest.response.body.$.appointment.appointmentId}}
@patientId = {{scheduleRequest.response.body.$.appointment.patientId}}

# @name scheduleRequest
POST http://{{url}}:{{apptserviceDaprPort}}/v1.0/invoke/appointment-service/method/v1/schedule HTTP/1.1
Content-Type: application/json

{
    "AppointmentId": "{{appointmentId}}",
    "PatientId": "{{patientId}}",
    "AppointmentDateTime": "2024-01-11T09:00:00",
    "PatientFirstName": "Matt",
    "PatientLastName": "Sheehan"
}
