@url= localhost
@apptserviceDaprPort = 5010

###
# @name scheduleRequest
POST http://{{url}}:{{apptserviceDaprPort}}/v1.0/invoke/appointment-service/method/schedule HTTP/1.1
Content-Type: application/json

{
    "AppointmentDateTime": "2024-01-11T08:00:00",
    "PatientFirstName": "Matt",
    "PatientLastName": "Sheehan",
    "Practitioner": "Dr. Acula"
}

###
@appointmentId = {{scheduleRequest.response.body.$.appointmentId}}
@patientId = {{scheduleRequest.response.body.$.patientId}}

# @name claimRequest
POST http://{{url}}:{{apptserviceDaprPort}}/v1.0/invoke/appointment-service/method/submitclaim HTTP/1.1
Content-Type: application/json

{
    "AppointmentId": "{{appointmentId}}",
    "Amount": 100.00
}

###
@topicName = ClaimSubmitted
POST http://{{url}}:{{apptserviceDaprPort}}/v1.0/publish/pubsub/{{topicName}} HTTP/1.1
Content-Type: application/json

{
    "appointmentId": "{{appointmentId}}",
    "patientId": "{{patientId}}",
    "claimAmount": 150.00
}